using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Text;

namespace Covid19Tracker.Models
{
    public class CountriesModel
    {
    public string countries { get; set; }
}
    //public class Countries
    //{
    //    public string Afghanistan { get; set; }
    //    public string AlandIslands { get; set; }
    //    public string Albania { get; set; }
    //    public string Algeria { get; set; }
    //    public string AmericanSamoa { get; set; }
    //    public string Andorra { get; set; }
    //    public string Angola { get; set; }
    //    public string Anguilla { get; set; }
    //    public string Antarctica { get; set; }
    //    public string AntiguaandBarbuda { get; set; }
    //    public string Argentina { get; set; }
    //    public string Armenia { get; set; }
    //    public string Aruba { get; set; }
    //    public string Australia { get; set; }
    //    public string Austria { get; set; }
    //    public string Azerbaijan { get; set; }
    //    public string Bahamas { get; set; }
    //    public string Bahrain { get; set; }
    //    public string Bangladesh { get; set; }
    //    public string Barbados { get; set; }
    //    public string Belarus { get; set; }
    //    public string Belgium { get; set; }
    //    public string Belize { get; set; }
    //    public string Benin { get; set; }
    //    public string Bermuda { get; set; }
    //    public string Bhutan { get; set; }
    //    public string Bolivia { get; set; }
    //    public string Bosnia { get; set; }
    //    public string Botswana { get; set; }
    //    public string BouvetIsland { get; set; }
    //    public string Brazil { get; set; }
    //    public string BritishIndianOceanTerritory { get; set; }
    //    public string BritishVirginIslands { get; set; }
    //    public string Brunei { get; set; }
    //    public string Bulgaria { get; set; }
    //    public string BurkinaFaso { get; set; }
    //    public string Burundi { get; set; }
    //    public string Cambodia { get; set; }
    //    public string Cameroon { get; set; }
    //    public string Canada { get; set; }
    //    public string CapeVerde { get; set; }
    //    public string CaymanIslands { get; set; }
    //    public string CentralAfricanRepublic { get; set; }
    //    public string Chad { get; set; }
    //    public string Chile { get; set; }
    //    public string China { get; set; }
    //    public string ChristmasIsland { get; set; }
    //    public string CocosIslands { get; set; }
    //    public string Colombia { get; set; }
    //    public string Comoros { get; set; }
    //    public string CookIslands { get; set; }
    //    public string CostaRica { get; set; }
    //    public string Croatia { get; set; }
    //    public string Cuba { get; set; }
    //    public string Curacao { get; set; }
    //    public string Cyprus { get; set; }
    //    public string CzechRepublic { get; set; }
    //    public string Czechia { get; set; }
    //    public string DemocraticRepublicoftheCongo { get; set; }
    //    public string Denmark { get; set; }
    //    public string Djibouti { get; set; }
    //    public string Dominica { get; set; }
    //    public string DominicanRepublic { get; set; }
    //    public string EastTimor { get; set; }
    //    public string Ecuador { get; set; }
    //    public string Egypt { get; set; }
    //    public string ElSalvador { get; set; }
    //    public string EquatorialGuinea { get; set; }
    //    public string Eritrea { get; set; }
    //    public string Estonia { get; set; }
    //    public string Ethiopia { get; set; }
    //    public string FalklandIslands { get; set; }
    //    public string FaroeIslands { get; set; }
    //    public string Fiji { get; set; }
    //    public string Finland { get; set; }
    //    public string France { get; set; }
    //    public string FrenczGuiana { get; set; }
    //    public string FrenchPolynesia { get; set; }
    //    public string FrenchSouthernTerritories { get; set; }
    //    public string Gabon { get; set; }
    //    public string Gambia { get; set; }
    //    public string Georgia { get; set; }
    //    public string Germany { get; set; }
    //    public string Ghana { get; set; }
    //    public string Gibraltar { get; set; }
    //    public string Greece { get; set; }
    //    public string Greenland { get; set; }
    //    public string Grenada { get; set; }
    //    public string Guadeloupe { get; set; }
    //    public string Guam { get; set; }
    //    public string Guatemala { get; set; }
    //    public string Guernsey { get; set; }
    //    public string GuineaBissau { get; set; }
    //    public string Guinea { get; set; }
    //    public string Guyana { get; set; }
    //    public string Haiti { get; set; }
    //    public string HeardIslandandMcDonaldIslands { get; set; }
    //    public string Honduras { get; set; }
    //    public string HongKong { get; set; }
    //    public string Hungary { get; set; }
    //    public string Iceland { get; set; }
    //    public string India { get; set; }
    //    public string Indonesia { get; set; }
    //    public string Iran { get; set; }
    //    public string Iraq { get; set; }
    //    public string Ireland { get; set; }
    //    public string IsleofMan { get; set; }
    //    public string Israel { get; set; }
    //    public string Italy { get; set; }
    //    public string IvoryCoast { get; set; }
    //    public string Jamaica { get; set; }
    //    public string Japan { get; set; }
    //    public string Jersey { get; set; }
    //    public string Jordan { get; set; }
    //    public string Kazakhstan { get; set; }
    //    public string Kenya { get; set; }
    //    public string Kiribati { get; set; }
    //    public string Kosovo { get; set; }
    //    public string Kuwait { get; set; }
    //    public string Kyrgyzstan { get; set; }
    //    public string Laos { get; set; }
    //    public string Latvia { get; set; }
    //    public string Lebanon { get; set; }
    //    public string Lesotho { get; set; }
    //    public string Liberia { get; set; }
    //    public string Libya { get; set; }
    //    public string Liechtenstein { get; set; }
    //    public string Lithuania { get; set; }
    //    public string Luxembourg { get; set; }
    //    public string Macao { get; set; }
    //    public string Macedonia { get; set; }
    //    public string Madagascar { get; set; }
    //    public string MainlandChina { get; set; }
    //    public string Malawi { get; set; }
    //    public string Malaysia { get; set; }
    //    public string Maldives { get; set; }
    //    public string Mali { get; set; }
    //    public string Malta { get; set; }
    //    public string MarshallIslands { get; set; }
    //    public string Martinique { get; set; }
    //    public string Mauritania { get; set; }
    //    public string Mauritius { get; set; }
    //    public string Mayotte { get; set; }
    //    public string Mexico { get; set; }
    //    public string Micronesia { get; set; }
    //    public string Moldova { get; set; }
    //    public string Monaco { get; set; }
    //    public string Mongolia { get; set; }
    //    public string Montenegro { get; set; }
    //    public string Montserrat { get; set; }
    //    public string Morocco { get; set; }
    //    public string Mozambique { get; set; }
    //    public string Myanmar { get; set; }
    //    public string Namibia { get; set; }
    //    public string Nauru { get; set; }
    //    public string Nepal { get; set; }
    //    public string Netherlands { get; set; }
    //    public string NewCaledonia { get; set; }
    //    public string NewZealand { get; set; }
    //    public string Nicaragua { get; set; }
    //    public string Niger { get; set; }
    //    public string Nigeria { get; set; }
    //    public string Niue { get; set; }
    //    public string NorfolkIsland { get; set; }
    //    public string NorthKorea { get; set; }
    //    public string NorthernMarianaIslands { get; set; }
    //    public string Norway { get; set; }
    //    public string Oman { get; set; }
    //    public string Pakistan { get; set; }
    //    public string Palau { get; set; }
    //    public string PalestinianTerritory { get; set; }
    //    public string Panama { get; set; }
    //    public string PapuaNewGuinea { get; set; }
    //    public string Paraguay { get; set; }
    //    public string Peru { get; set; }
    //    public string Philippines { get; set; }
    //    public string Pitcairn { get; set; }
    //    public string Poland { get; set; }
    //    public string Portugal { get; set; }
    //    public string PuertoRico { get; set; }
    //    public string Qatar { get; set; }
    //    public string RepublicoftheCongo { get; set; }
    //    public string Reunion { get; set; }
    //    public string Romania { get; set; }
    //    public string Russia { get; set; }
    //    public string Rwanda { get; set; }
    //    public string SaintBarthelemy { get; set; }
    //    public string SaintHelena { get; set; }
    //    public string SaintKittsandNevis { get; set; }
    //    public string SaintLucia { get; set; }
    //    public string SaintMartin { get; set; }
    //    public string SaintPierreandMiquelon { get; set; }
    //    public string SaintVincentandtheGrenadines { get; set; }
    //    public string Samoa { get; set; }
    //    public string SanMarino { get; set; }
    //    public string SaoTomeandPrincipe { get; set; }
    //    public string SaudiArabia { get; set; }
    //    public string Senegal { get; set; }
    //    public string Serbia { get; set; }
    //    public string Seychelles { get; set; }
    //    public string SierraLeone { get; set; }
    //    public string Singapore { get; set; }
    //    public string SintMaarten { get; set; }
    //    public string Slovakia { get; set; }
    //    public string Slovenia { get; set; }
    //    public string SolomonIslands { get; set; }
    //    public string Somalia { get; set; }
    //    public string SouthAfrica { get; set; }
    //    public string SouthGeorgiaandtheSouthSandwichIslands { get; set; }
    //    public string SouthKorea { get; set; }
    //    public string SouthSudan { get; set; }
    //    public string Spain { get; set; }
    //    public string SriLanka { get; set; }
    //    public string Sudan { get; set; }
    //    public string Suriname { get; set; }
    //    public string SvalbardandJanMayen { get; set; }
    //    public string Swaziland { get; set; }
    //    public string Sweden { get; set; }
    //    public string Switzerland { get; set; }
    //    public string Syria { get; set; }
    //    public string Taiwan { get; set; }
    //    public string Tajikistan { get; set; }
    //    public string Tanzania { get; set; }
    //    public string Thailand { get; set; }
    //    public string Togo { get; set; }
    //    public string Tokelau { get; set; }
    //    public string Tonga { get; set; }
    //    public string TrinidadandTobago { get; set; }
    //    public string Tunisia { get; set; }
    //    public string Turkey { get; set; }
    //    public string Turkmenistan { get; set; }
    //    public string TurksandCaicosIslands { get; set; }
    //    public string Tuvalu { get; set; }
    //    public string U_S_VirginIslands { get; set; }
    //    public string Uganda { get; set; }
    //    public string Ukraine { get; set; }
    //    public string UnitedArabEmirates { get; set; }
    //    public string UnitedKingdom { get; set; }
    //    public string UnitedStatesMinorOutlyingIslands { get; set; }
    //    public string Uruguay { get; set; }
    //    public string US { get; set; }
    //    public string Uzbekistan { get; set; }
    //    public string Vanuatu { get; set; }
    //    public string Vatican { get; set; }
    //    public string Venezuela { get; set; }
    //    public string Vietnam { get; set; }
    //    public string WallisandFutuna { get; set; }
    //    public string Western_Sahara { get; set; }
    //    public string Yemen { get; set; }
    //    public string Zambia { get; set; }
    //    public string Zimbabwe { get; set; }
    //}

}









